name: 'sonarqube-base'

services:
  sonarqube:
    container_name: sonarqube-container
    hostname: sonarqube-server
    image: sonarqube/server:dev
    build:
      context: .
      dockerfile: ./infra/docker/sonarqube/Dockerfile
      cache_from:
        - sonarqube/server:cache
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - '9000:9000'
    volumes:
      - sonarqube-data-volume:/opt/sonarqube/data
      - sonarqube-extensions-volume:/opt/sonarqube/extensions
      - sonarqube-logs-volume:/opt/sonarqube/logs
    depends_on:
      - sonarqube-db

  sonarqube-db:
    container_name: sonarqube-db-container
    hostname: sonarqube-db-server
    image: sonarqube/db:dev
    build:
      context: .
      dockerfile: ./infra/docker/sonarqube-db/Dockerfile
      cache_from:
        - sonarqube/db:cache
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonarqube-postgresql-volume:/var/lib/postgresql
      - sonarqube-postgresql-data-volume:/var/lib/postgresql/data

volumes:
  sonarqube-data-volume:
    name: sonarqube-data
    driver: local
  sonarqube-extensions-volume:
    name: sonarqube-extensions
    driver: local
  sonarqube-logs-volume:
    name: sonarqube-logs
    driver: local
  sonarqube-postgresql-volume:
    name: sonarqube-postgresql
    driver: local
  sonarqube-postgresql-data-volume:
    name: sonarqube-postgresql-data
    driver: local
